# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLqnobgH67Sw8j4W2BvY3nR0dkXAGDvo
"""

# Quick sort code with gradio UI

import gradio as gr

# Quick Sort function
def quickSort(arr):
  # Base Case: if list has 0 or 1 items means its already sorted

  if len(arr) <= 1:

    return arr

  # choose the pivot
  pivot_index = len(arr) // 2

  pivot = arr[pivot_index]

  #Create 3 lists for partitioning
  left = []
  middle = []
  right = []

  # loop through each value and place in right partition
  for value in arr:
    if value < pivot:
      left.append(value)

    elif value == pivot:
      middle.append(value)

    else:
      right.append(value)

  # recursively sort left and right partitions
  sortedleft = quickSort(left)

  sortedright = quickSort(right)

  #combine all partitions and return final sorted list
  return sortedleft + middle + sortedright

# Function to handle user input from gradio
def numberSort(numberString):

  #split user input by commas to get items

  parts = numberString.split(',')

  num_list = []

  # convert each item into an integer
  for item in parts:
    item = item.strip() #remove spaces

    #Check if item is a valid integer or not
    if item.isdigit() or (item.startswith('-') and item[1:].isdigit()):

     num_list.append(int(item))

    else:
      return "Invalid Input. Please enter numbers seperated by commas"

  #Sort list using quick sort function
  sorted_list = quickSort(num_list)

  # Turn sorted numbers into a single clean string
  result = ""

  for number in sorted_list:

    result += str(number) + " "

  return result.strip() # return final value without space


#gradio UI
app = gr.Interface(
  fn=numberSort,   # Function to run

  inputs=gr.Textbox(label = "Enter Numbers(No commas)",
                    placeholder = "e.g, 10, 4, 2, 1, 9",),
  outputs = gr.Textbox(label = "Sorted Output"),
  title = "Quick Sort Demonstrater",
  description = " Enter a list of numbers like: 10, 5, 2, 4, 3 and see them sorted using Quick Sort"


)
#launch web app
app.launch()